services:
  nodeapp: 
    container_name: nodeappcontainer
    build: .
    image: node-ap:v1
    volumes: 
      - $HOME/nodeapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: //
      DB_PORT: 3306
      DB_USER: //
      DB_PASSWORD: //
      DB_NAME: //
      DB_CONNECTION_LIMIT: 20
      SERVER_PORT: 3000
      SERVICE_TAGS: dev
      SERVICE_NAME: nodeappservice
