# version: "1.0"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 3000:3000
#     volumes:
#       - .:/app
#       - '/app/node_modules'
#     depends_on:
#       - mysql_server
      
#   mysql_server:
#     image: mysql:8.0
#     networks:
#       - frontend
#       - backend
#     ports:
#       - "30001:8005"
#     environment:
#       - MYSQL_DATABASE=test_db
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=root
#       - MYSQL_ROOT_PASSWORD=secret
#     volumes:
#       - ./www/:/var/www/html/
#       # Volume de mysql / etc
#     container_name: mysql_container
  
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:4.7
#     depends_on:
#       - mysql_server
#     networks:
#       - backend
#       - frontend
#     ports:
#       - "30002:80"
#     environment:
#       - PMA_HOST=mysql_container
#       - PMA_PORT= 3306
#     volumes:
#       - /sessions
#     container_name: phpmyadmin_container
#   networks:
#     frontend:
#     backend:

#Nouveau
services:
  # mysqldb: 
  #   image: mysql:8.0
  #   container_name: mysql_container
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: unless-stopped
  #   volumes: 
  #     - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
  #     - $HOME/database:/var/lib/mysql 
  #     #revoir le $HOME 
  #   ports: 
  #     - 3306:3306
  #   expose:
  #     - 3306
  #   environment:
  #     - MYSQL_DATABASE=test_db
  #     - MYSQL_USER=admin
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_ROOT_PASSWORD=password
  #     - SERVICE_TAGS=dev
  #     - SERVICE_NAME=mysqldb
  #     - SERVER_PORT=3000
  #   networks:
  #     - backend

  # phpmyadmin:
  #   image: phpmyadmin
  #   depends_on:
  #     - mysqldb
  #   networks:
  #     - backend
  #   ports:
  #     - "30002:80"
  #   environment:
  #     - PMA_HOST=mysql_container
  #     - PMA_PORT= 3306
  #   volumes:
  #     - /sessions
  #   container_name: phpmyadmin-container
  
  nodeapp: 
    container_name: nodeappcontainer
    build: .
    image: node-ap:v1
    volumes: 
      - $HOME/nodeapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: 109.234.161.47
      DB_PORT: 3306
      DB_USER: rzgf6652_admin
      DB_PASSWORD: Karl1991!
      DB_NAME: rzgf6652_test_db
      DB_CONNECTION_LIMIT: 20
      SERVER_PORT: 3000
      SERVICE_TAGS: dev
      SERVICE_NAME: nodeappservice
    # depends_on:
    #   - mysqldb
  

# networks:
#   backend:
#     driver: bridge



      